#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'ruby_build'

# external

cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv.git'

cookbook 'chefenv',
  :git => 'https://github.com/shimizukawa/chef-chefenv.git'

cookbook 'shimizukawa-env',
  :git => 'https://github.com/shimizukawa/chef-shimizukawa-env.git'

cookbook 'myrecipe',
  :git => 'https://github.com/shimizukawa/chef-myrecipe.git'

